version: '3.2'

services:
  nginx: 
    image: nginx:latest
    container_name: sfia_pdp_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  sfiapdp:
    build: "./"
    container_name: sfiapdp
    restart: always
    expose:
      - "80"